import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import StoreProvider from "./StoreProvider";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Refedo - Reference Document Redefined",
    description:
        "Generated by bnminh3107 based on tutorials from Antonio Erdeljac",
    icons: {
        icon: ["/favicon.ico?v=4"],
        apple: ["/apple-touch-icon.png?v=4"],
        shortcut: ["/apple-touch-icon.png"],
    },
    manifest: "/site.webmanifest",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await auth();
    return (
        <SessionProvider session={session}>
            <StoreProvider>
                <html lang="en">
                    <body className={inter.className}>
                        <div className="flex flex-col min-h-screen gap-y-10 items-center justify-center overflow-y-auto bg-slate-50">
                            <Navbar />
                            <div className="flex-grow">{children}</div>
                        </div>
                        <Toaster />
                    </body>
                </html>
            </StoreProvider>
        </SessionProvider>
    );
}
